copyright = "© Your Name"
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Auguste Photographie'
theme = "hugo-theme-gallery"
[params]
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/21th.streetshots/"
    github = "https://github.com/"
    email = "mailto:user@example.com"
    
