name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Surge
        run: |
          npm install --global surge
          surge ./ auguste-photography.surge.sh --token ${{ secrets.SURGE_TOKEN }}
